# Generated by Django 3.2.4 on 2021-06-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JustTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mom', models.CharField(max_length=250, verbose_name='mom')),
                ('dad', models.CharField(max_length=250, verbose_name='dad')),
                ('sisterStuckedUnderTheTable', models.CharField(max_length=250, verbose_name='sisterStucked')),
            ],
        ),
    ]
